export const wordsWithHints = [
    { word: "bug", hint: "An error or flaw in a program that causes it to behave unexpectedly." },
    { word: "debugging", hint: "The process of identifying and fixing errors in a program." },
    { word: "compiler", hint: "A program that translates source code into machine code." },
    { word: "interpreter", hint: "A program that executes code directly, line by line." },
    { word: "framework", hint: "A pre-built set of tools and libraries used to create applications." },
    { word: "library", hint: "A collection of pre-written code that can be reused in different projects." },
    { word: "syntax", hint: "The set of rules that dictate the structure of a programming language." },
    { word: "variable", hint: "A named storage location used to store data in a program." },
    { word: "iteration", hint: "The process of repeatedly executing a set of statements in a program." },
    { word: "object", hint: "A self-contained unit that contains both data and functions." },
    { word: "inheritance", hint: "A concept in object-oriented programming where a class inherits properties and behaviors from another class." },
    { word: "polymorphism", hint: "The ability of objects of different classes to be treated as objects of a common super class." },
    { word: "database", hint: "A structured collection of data stored and organized for easy retrieval." },
    { word: "API", hint: "Application Programming Interface, a set of rules and protocols for building and interacting with software components." },
    { word: "server", hint: "A computer or software that provides services to other computers or clients." },
    { word: "client", hint: "A computer or software that requests services or resources from a server." },
    { word: "data structure", hint: "A way of organizing and storing data for efficient access and modification." },
    { word: "javascript", hint: "A popular scripting language often used for web development." },
  { word: "python", hint: "A versatile and beginner-friendly programming language." },
  { word: "java", hint: "A widely-used, object-oriented programming language." },
  { word: "html", hint: "The standard markup language for creating web pages." },
  { word: "css", hint: "A stylesheet language used to control the presentation of web documents." },
  { word: "ruby", hint: "A dynamic, open-source programming language with a focus on simplicity." },
  { word: "php", hint: "A server-side scripting language for web development." },
  { word: "sql", hint: "A language used for managing and querying relational databases." },
  { word: "typescript", hint: "A strict syntactical superset of JavaScript, adding static types." },
  { word: "csharp", hint: "A modern, object-oriented programming language developed by Microsoft." },
  { word: "swift", hint: "A programming language designed for building iOS and macOS applications." },
  { word: "cpp", hint: "An extension of the C programming language often used for system programming." },
  { word: "git", hint: "A distributed version control system used for tracking changes in code." },
  { word: "docker", hint: "A platform for developing, shipping, and running applications in containers." },
  { word: "react", hint: "A JavaScript library for building user interfaces." },
  { word: "angular", hint: "A framework for building web applications, developed by Google." },
  { word: "nodejs", hint: "An open-source, cross-platform runtime environment for server-side JavaScript." },
  { word: "algorithm", hint: "A set of step-by-step instructions for solving a problem." },
  { word: "variable", hint: "A named storage location used to store data in a program." },
  { word: "function", hint: "A block of code that performs a specific task." }
];


